import java.io.FileInputStream
import java.util.Properties

apply(plugin = "maven-publish")

val publishInfo = Properties()
val publishPropertiesFile = rootProject.file("publish.properties")
if (publishPropertiesFile.exists()) {
    publishInfo.load(FileInputStream(publishPropertiesFile))
}

val libVersion = getVersionFromFile("version.txt", "0.2.1")

publishing {
    repositories {
        mavenLocal()
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/egeniq/app-remote-config-android")
            credentials {
                username = publishInfo["token.name"]?.toString() ?: ""
                password = publishInfo["token.value"]?.toString() ?: ""
            }
        }
    }
    
    // Configure all publications created by the KMP plugin
    publications.withType<MavenPublication>().configureEach {
        groupId = "com.egeniq"
        version = libVersion
        
        //artifactId will be automatically generated by project name and target suffix (e.g., "AppRemoteConfig-jvm")
    }
}

fun getVersionFromFile(
    path: String,
    defaultValue: String,
): String {
    val versionFile = file(path)
    return if (versionFile.exists()) {
        versionFile.readText().trim()
    } else {
        defaultValue
    }
}
